"""removing a column

Revision ID: 684b36d6ce41
Revises: 2a2cbf5074dc
Create Date: 2024-12-21 12:32:13.043367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684b36d6ce41'
down_revision = '2a2cbf5074dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
